apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  serviceAccountName: argo
  entrypoint: diamond
  templates:
  - name: echo
    inputs:
      parameters:
        - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: "Initializing Workflow"}]
      - name: B
        dependencies: [A]
        template: coinflip-B
      - name: C
        dependencies: [A]
        template: coinflip-C
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: "Done with Worflow"}]
  - name: flip-coin
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)

  - name: coinflip-C
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: heads
        template: echo
        arguments:
          parameters: [{name: message, value: "It was {{steps.flip-coin.outputs.result}}"}]
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails
        template: coinflip-C
        when: "{{steps.flip-coin.outputs.result}} == tails"
  - name: coinflip-B
    steps:
    - - name: flip-coin
        template: flip-coin
    - - name: heads
        template: coinflip-B
        when: "{{steps.flip-coin.outputs.result}} == heads"
    - - name: tails
        template: echo
        arguments:
          parameters: [{name: message, value: "It was {{steps.flip-coin.outputs.result}}"}]
        when: "{{steps.flip-coin.outputs.result}} == tails"
